config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :users

  resources :blog_posts, only: [:show, :index]

  namespace :admin do
    resources :users, only: [:index]
    resources :blog_posts, only: [:new, :create, :edit, :update, :destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: %w(user admin)
  enum pc_position: %w(consul proconsul annotator scribe sergeant_at_arms custodian)

  has_many :blog_posts

  def is_admin?
    self.admin?
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  load_and_authorize_resource

  private
    def not_authenticated
      redirect_to new_user_session_path, alert: "Please login first"
    end
end

app/controllers/admin/blog_posts_controller.rb
class Admin::BlogPostsController < ApplicationController
  before_action :is_admin?

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    if @blog_post.save
      flash[:notice] = "Blog Post Created!"
      redirect_to blog_posts_path
    else
      flash[:notice] = "An Error Occurred!"
      redirect to :new
    end
  end

  private
  def blog_post_params
    params.require(:blog_post).permit(:title, :body, :user_id)
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
    binding.pry
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def is_admin?
    current_user.admin?
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @blog_posts = BlogPost.all
  end

  def show
    @blog_post = BlogPost.find_by(id: params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/blog_posts/new.html.erb
<%= simple_form_for @blog_post, url: admin_blog_posts_path , :method => :post do |f| %>
  <%= f.input :title, label: 'Enter a title', error: 'Title is mandatory, please write one.' %>
  <%= f.input :body, as: :text, label: 'Write your post!' %>
  <%= f.button :submit %>
<% end %>

app/views/admin/dashboard/index.html.erb
<h1>Admin::Dashboard#index</h1>

app/views/admin/users/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>First Name </th>
      <th>Last Name </th>
      <th>Email</th>
      <th>Beta Number </th>
      <th>Role </th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.beta_number %></td>
        <td><%= user.role.humanize %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/blog_posts/index.html.erb
<% @blog_posts.each do |post| %>
  <h1><%= link_to post.title, blog_post_path(post) %></h1>
  <p><%= post.body %></p>
<% end %>

app/views/blog_posts/show.html.erb
<h1><%= @blog_post.title %></h1>
<p><%= @blog_post.body %></h1>

app/views/home/index.html.erb
<% if current_user && current_user.admin? %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Delta Kappa Phi</title>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<nav class="navbar navbar-default">
  <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-text navbar-left">
        <% if user_signed_in? && current_user.is_admin? %>
          <%= link_to "Users", admin_users_path %>
        <% end %>
      </div>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path do %>
          <%= image_tag("shield.png", border: 0, class: "shield visible-lg visible-md") %>
        <% end %>
      </div>
      <div class="navbar-text navbar-right">
        <% if user_signed_in? %>
          <% if current_user.is_admin? %>
            <%= link_to('New Post', new_admin_blog_post_path) %>
          <% end %>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        <% else %>
          <%= link_to('Login', new_user_session_path)  %>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<body>
  <div class=body-container>
    <%= yield %>
  </div>
</body>
</html>